### ISSUE TITLE
Training stopping criteria 

### ISSUE THREAD

**Issue by AbdouMechraoui** [nv-tlabs/semanticGAN_code#20]
I would like to ask about the stopping criteria for `train_seg_gan.py`. So after every 2000 iterations, I get the values of FID, IS, d_img val, and d_seg val. I'm not quite sure what the last two are for? It seems like it's the averaged prediction of the segmentation discriminator, and image discriminator. 

Usually, I stop training when the images look appealing, and the FID score plateaus. Do the other scores play any role? How to evaluate the segmentation branch during training? I'm in a situation where FID is low, but segmentation visual inspection is bad. 

Any insight would be highly appreciated :)

**Comment by lidaiqing** [comment]
Hi @AbdouMechraoui , usually we found segmentation branch accuracy is correlated to the FID score of images. One way to monitor it is checking the discriminator fake/real score of the segmentation branch, if the two scores start diverging, it is likely the discriminator cannot provide useful information to the generator anymore. Another way is to monitor the sample quality, since samples are drawn from the same latent codes, you can check the label quality from each iteration. As for your case, if the segmentation does not improve over time, it is likely some bugs when you process it. You could check if your segmentation is normalized to -1 to 1 etc.

**Comment by AbdouMechraoui** [comment]
Indeed, I had some issues with the way I fed my labels. Namely, I was using jpg, which is needless to say dumb x). So, I made sure the data loader is accepting my desired classes, and now it converges wonderfully. Thank you so much for your input, it helped me a lot :)
